// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psvevuasvigzoxtqtljy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzdmV2dWFzdmlnem94dHF0bGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwOTc3NjksImV4cCI6MjA3NDY3Mzc2OX0.8Ky-wa0s4rSnrfw69WjvV2PytJcoVtMircq6y3SFelU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});